steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/elegant-wavelet-373717/github.com/arslaan/invmania:$SHORT_SHA','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/elegant-wavelet-373717/github.com/arslaan/invmania:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'invmania-service', '--region=us-central1', '--platform=managed', '--image=gcr.io/elegant-wavelet-373717/github.com/arslaan/invmania:$SHORT_SHA']
